<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RevitVersion Condition="'$(RevitVersion)' == ''">2027</RevitVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2021'">2.6.0.8481</DynamoVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2022'">2.7.0.9206</DynamoVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2023'">2.12.0.5650</DynamoVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2024'">2.15.0.5383</DynamoVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2025'">2.16.0.2501</DynamoVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2026'">2.17.0.3493</DynamoVersion>
    <DynamoVersion Condition="'$(RevitVersion)' == '2027'">2.18.0.4827</DynamoVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>BeyondDynamoInstaller</RootNamespace>
    <AssemblyName>BeyondDynamoInstaller</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.4" />
    <PackageReference Include="Costura.Fody" Version="5.7.0" />
    <PackageReference Include="DynamoVisualProgramming.Core" Version="$(DynamoVersion)" />
    <PackageReference Include="DynamoVisualProgramming.DynamoCoreNodes" Version="$(DynamoVersion)" />
    <PackageReference Include="DynamoVisualProgramming.DynamoServices" Version="$(DynamoVersion)" />
    <PackageReference Include="DynamoVisualProgramming.WpfUILibrary" Version="$(DynamoVersion)" />
    <PackageReference Include="DynamoVisualProgramming.ZeroTouchLibrary" Version="$(DynamoVersion)" />
    <PackageReference Include="Fody" Version="6.5.5" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.1.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="NUnit" Version="2.6.3" />
    <PackageReference Include="Prism" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" Visible="false" />
    <Content Include="FodyWeavers.xml" />
  </ItemGroup>
</Project>
